server:
  port: 8089

management:
  security:
    enabled: false

spring:
  application:
    name: ROOM-OCCUPANCY-MANAGER

logging:
  level:
    root: INFO

guests: [23, 45, 155, 374, 22, 99, 100, 101, 115, 209]

app:
  name: Room Occupancy Manager
  api:
    title: Room Occupancy Manager API
    version: 1.0.0
    description: Room Occupancy Calculator
    base-package: com.rooms.occupancy.manager.controller
    contact-name: Ravichandra Penumuru
    contact-email: rc.reddy@outlook.com
    logging:
      enable: true
      url-patterns: /api/*
      requestIdParamName: reqId